# Generated by Django 4.0.4 on 2022-05-14 13:06

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usersavedplacesmodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedplacesmodel',
            name='image',
            field=models.ImageField(upload_to=apps.user.models.upload_to, verbose_name='images/'),
        ),
    ]
