# Generated by Django 4.0.4 on 2022-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.FloatField(max_length=11)),
                ('password', models.CharField(max_length=512)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('push_token', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
