# Generated by Django 4.0.4 on 2022-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userauthmodel_groups_userauthmodel_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
