# Generated by Django 4.0.4 on 2022-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userauthmodel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
