# Generated by Django 4.0.4 on 2022-05-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_userauthmodel_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthmodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
