# Generated by Django 4.0.4 on 2022-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_userauthmodel_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthModel',
        ),
    ]
